-- Legacy seed data is normally generated by Python into CSV files.
-- This file documents expected legacy domains.

-- segment_code: RET, PRM, SME
-- acct_type: CUR, SVG
-- curr: CHF, EUR, USD

SELECT 'legacy_reference_values_documented' AS seed_status;
